export default {
    'HTML5_NOT_SUPPORTED':1,
    'DRM_NOT_AVAILABLE': 2,
    'ERROR_PLAYING_SOURCE': 3,
    'FLASH_NOT_INSTALLED': 4,
    'NOT_AVAILABLE_ON_WEB': 5,
    'GEO_BLOCKED': 6,
    'VIDEO_STREAMING_NOT_SUPPORTED': 7,
    'DRM_NOT_SUPPORTED': 8,
    'CATCHUP_NOT_PLAYABLE': 9,
    'FUTURE_PROGRAM': 10
}